"""add chapter.image_url

Revision ID: 061f1e8196a1
Revises: 05930e8766cf
Create Date: 2025-10-03 19:43:44.438869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061f1e8196a1'
down_revision = '05930e8766cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
