"""add oauth fields to user

Revision ID: 57a926363238
Revises: 061f1e8196a1
Create Date: 2025-10-16 22:12:30.478138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a926363238'
down_revision = '061f1e8196a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('discord_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('favorite_book', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('genre_preferences', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_user_discord_id', ['discord_id'])
        batch_op.create_unique_constraint('uq_user_github_id', ['github_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_discord_id', type_='unique')
        batch_op.drop_constraint('uq_user_github_id', type_='unique')
        batch_op.drop_column('genre_preferences')
        batch_op.drop_column('favorite_book')
        batch_op.drop_column('profile_picture_url')
        batch_op.drop_column('discord_id')
        batch_op.drop_column('github_id')

    # ### end Alembic commands ###
